---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - yarn test
  - ./node_modules/.bin/ember deploy production --activate --verbose

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./tmp/deploy-dist
  on:
    branch: master
